[package]
name = "udp2sse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-web-lab = "0.19.1"
base64 = "0.21.2"
futures-util = "0.3.28"
